# Generated by Django 2.2.12 on 2020-10-31 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('page_level', models.IntegerField()),
                ('page_template', models.CharField(default='default', max_length=200)),
                ('page_name_en', models.CharField(default='', max_length=200)),
                ('page_name_fr', models.CharField(default='', max_length=200)),
                ('page_content_en', models.TextField(blank=True, default='')),
                ('page_content_fr', models.TextField(blank=True, default='')),
                ('custom_js_css_en', models.TextField(blank=True, default='')),
                ('custom_js_css_fr', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page')),
            ],
        ),
    ]
