# Generated by Django 2.2.12 on 2020-10-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201031_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name_en',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
