# Generated by Django 2.2.12 on 2020-10-31 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20201031_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='paage_title_en',
            new_name='page_title_en',
        ),
    ]
