# Generated by Django 3.1.3 on 2020-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20201031_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_template',
            field=models.CharField(choices=[('DF', 'Default'), ('NS', 'No Sidebar')], default='DF', max_length=200),
        ),
    ]
