# Generated by Django 3.1.3 on 2020-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20201119_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('tag', models.CharField(max_length=200)),
                ('eventDay', models.DateField()),
            ],
        ),
    ]
