# Generated by Django 3.1.3 on 2020-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBMCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(max_length=200)),
                ('url', models.TextField(max_length=200)),
                ('version', models.TextField(max_length=100)),
            ],
        ),
    ]
