# Generated by Django 3.1.3 on 2020-11-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
    ]
