# Generated by Django 3.1.3 on 2020-11-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_remove_job_job_id'),
        ('cms', '0009_ibmcredential'),
    ]

    operations = [
    ]
