# Generated by Django 3.1.3 on 2020-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_merge_20201128_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='section',
        ),
        migrations.RemoveField(
            model_name='job',
            name='short_description',
        ),
        migrations.AddField(
            model_name='job',
            name='english_long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='english_section',
            field=models.CharField(default='section', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='english_short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='french_long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='french_section',
            field=models.CharField(default='section', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='french_short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
