# Generated by Django 3.1.3 on 2020-12-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20201205_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='english_long_description',
            new_name='english_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='english_short_description',
            new_name='english_title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='french_long_description',
            new_name='french_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='french_short_description',
            new_name='french_title',
        ),
    ]
