# Generated by Django 3.1.3 on 2020-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsDay',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='english_title',
            field=models.CharField(default='section', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='french_title',
            field=models.CharField(default='section', max_length=100),
        ),
    ]
