# Generated by Django 3.1.3 on 2020-12-09 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20201208_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsDay',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='english_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='french_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
